
modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="tistheseason"
version="1.0.3"
displayName="Tis the Season"
logoFile="icon.png"
credits="Mod made for MMD WinterJam 2022"
authors="Vashal"
description='''
Santa is coming to town and bringing toys for all who were good this year!
'''
[[dependencies.tistheseason]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tistheseason]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tistheseason]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.34,)"
    ordering="BEFORE"
    side="BOTH"
